-- create database
create database ageas;
use ageas;
select * from insurance;

DESCRIBE INSURANCE;

-- FIND THE MIN AND MAX AGE OF CUSTOMER 
SELECT MIN(AGE) AS "MINIMUM AGE", 
MAX(AGE) AS "MAXIMIM AGE" FROM INSURANCE;

-- FIND THE MIN AND MAX CHARGES OF INSURANCE
SELECT MIN(CHARGES) AS "MINIMUM CHARGES OF POLICY", 
MAX(CHARGES) AS "MAXIMUM CHARGES OF POLICY" FROM INSURANCE;

-- Find MIN AND MAX NUMBER OF CHILDREN
SELECT MIN(CHILDREN) AS "MINIMUM NO. OF CHILDREN", 
MAX(CHILDREN) AS "MAXIMUM NO. OF CHILDREN" FROM INSURANCE;

-- MIN AND MAX BMI
SELECT MIN(BMI) AS "MINIMUM BODY MASS INDEX",
MAX(BMI) AS "MAXIMUM BODY MASS INDEX" FROM INSURANCE;

-- FIND STATUS OF BMI WITH CONDITION BMI <= 18.5
SELECT COUNT(*) AS "UNDERWEIGHT" FROM INSURANCE 
WHERE BMI <= 18.5;

-- COUNT BMI BETWEEN 18.6 AND 24.99
SELECT COUNT(*) AS "NORMAL WEIGHT "FROM INSURANCE 
WHERE BMI BETWEEN 18.6 AND 24.99;

-- COUNT BMI BETWEEN 25 AND 29.99
SELECT COUNT(*) AS "NORMAL WEIGHT "FROM INSURANCE 
WHERE BMI BETWEEN 25 AND 29.99;

-- COUNT BMI >= 30
SELECT COUNT(*) AS "NORMAL WEIGHT "FROM INSURANCE 
WHERE BMI >= 30;

-- COUNT TOTAL NUMBER OF FEMALE AND MALE  
SELECT COUNT(SEX) AS "NO. OF FEMALE" FROM INSURANCE
WHERE SEX="FEMALE";
SELECT COUNT(SEX) AS "NO. OF MALE" FROM INSURANCE
WHERE SEX="MALE";

-- COUNT NUMBER OF SMOKER AND NON - SMOKER
SELECT COUNT(SMOKER) AS "NO. OF SMOKER" FROM INSURANCE
WHERE SMOKER="YES";
SELECT COUNT(SMOKER) AS "NO. OF NON-SMOKER" FROM INSURANCE
WHERE SMOKER="NO";
SELECT * FROM INSURANCE;

-- COUNT BY REGION
SELECT COUNT(REGION) AS "NO. OF SOUTH WEST CUSTOMER"
FROM INSURANCE WHERE REGION = "SOUTHWEST";
SELECT COUNT(REGION) AS "NO. OF SOUTH EAST CUSTOMER"
FROM INSURANCE WHERE REGION = "SOUTHEAST";
SELECT COUNT(REGION) AS "NO. OF NORTH WEST CUSTOMER"
FROM INSURANCE WHERE REGION = "NORTHWEST";
SELECT COUNT(REGION) AS "NO. OF NORTH EAST CUSTOMER"
FROM INSURANCE WHERE REGION = "NORTHEAST";


-- FEMALE AND MALE CUSTOMER ACCORDING TO BMI 
SELECT BMI AS "BMI", SEX AS "GENDER" FROM INSURANCE
GROUP BY SEX, BMI;
-- SMOKER OR NON- SMOKER CUSTOMER WITH BMI
SELECT BMI AS "BMI", SMOKER AS "SMOKER" FROM INSURANCE 
GROUP BY BMI, SMOKER;

-- FIND THE AVERAGE CHARGES ACCORDING TO GENDER 
SELECT SEX, AVG(CHARGES) AS "AVERAGE CHARGES ACCORDING TO GENDER"
FROM INSURANCE GROUP BY SEX;

-- FIND THE SUM OF CHARGES ACCORDING TO GENDER 
SELECT SEX, SUM(CHARGES) AS "SUM OF CHARGES ACCORDING TO GENDER"
FROM INSURANCE GROUP BY SEX;

-- FIND THE SUM OF CHARGES ACCORDING TO REGION
SELECT REGION, SUM(CHARGES) AS "SUM OF CHARGES ACCORDING TO REGION"
FROM INSURANCE GROUP BY REGION;

-- FIND THE SUM OF CHARGES ACCORDING TO SMOKER 
SELECT SMOKER, SUM(CHARGES) AS "SUM OF CHARGES ACCORDING TO SMOKER"
FROM INSURANCE GROUP BY SMOKER;

-- COUNT GENDER WHO'S BMI <= 30, GROUPING WITH SMOKER 
SELECT SMOKER, SEX, COUNT(SEX) FROM INSURANCE WHERE 
BMI <= 30 GROUP BY SMOKER, SEX;

-- COUNT GENDER WHO'S BMI >= 30, GROUPING WITH SMOKER
SELECT SMOKER, SEX, COUNT(SEX) FROM INSURANCE WHERE 
BMI >= 30 GROUP BY SMOKER, SEX;

-- COUNT GENDER WHO'S BMI < 18.5, GROUPING WITH SMOKER
SELECT SMOKER, SEX, COUNT(SEX) FROM INSURANCE WHERE 
BMI < 18.5 GROUP BY SMOKER, SEX;
SELECT * FROM INSURANCE;

-- COUNT GENDER WHO'S BMI B/W 18.6 AND 24.99, GROUPING WITH SMOKER
SELECT SMOKER, SEX, COUNT(SEX) FROM INSURANCE
WHERE BMI BETWEEN 18.6 AND 24.99 GROUP BY SMOKER, SEX;

-- FIND WHO PAY HIGH CHRAGES ACCORDING TO SMOKER, AGE AND BMI 
-- MOSTLY SMOKER PAY HIGH CHARGES 
-- ABOVE AGE OF 40 PAY HIGH CHARGES THERE  
-- ABOVE 25 BMI PAY HIGH CHARGES
SELECT * FROM INSURANCE 
ORDER BY CHARGES DESC;

-- CREATE CALCULATOR TO CALCULATE BMI
DELIMITER &&
CREATE PROCEDURE HEALTH(BMIVALUE double)
BEGIN
IF(BMIVALUE > 30) THEN 
SELECT "OBESITY AND CHARGES WAS HIGH" ;
ELSEIF(BMIVALUE >= 25 AND BMIVALUE <= 29.99) THEN
SELECT "OVERWEIGHT AND MOSTLY CHARGES WAS HIGH";
ELSEIF(BMIVALUE >= 18.6 AND BMIVALUE <= 24.99) THEN
SELECT "HEALTHY PEOPLE AND CHARGES IS NORMAL";
ELSE
SELECT "UNDERWEIGHT AND CAHRGE IS HIGH";
END IF;
END &&
delimiter ;

call health(25);

-- FIND THE MALE CUSTOMER WHO ARE NON- SMOKER AND BMI LESS THAN 30?
SELECT * FROM INSURANCE WHERE SEX= "MALE" AND
BMI <30 AND SMOKER = "NO" ;

-- FIND THE FEMALE CUSTOMER WHO ARE NON- SMOKER AND BMI LESS THAN 30?
SELECT * FROM INSURANCE WHERE SEX= "FEMALE" AND
BMI <30 AND SMOKER = "NO" ;